import { FaseRef, RotasiHptRef, MelonAppData } from './types';

// Tabel Referensi Fase sesuai spesifikasi persis
export const TABEL_REFERENSI_FASE: FaseRef[] = [
  {
    id: 'awal',
    hstMin: 0,
    hstMax: 7,
    fase: 'Fase Awal (Adaptasi)',
    ecMin: 0.8,
    ecMax: 0.8,
    ppm500Min: 400,
    ppm500Max: 400,
    ppm700Min: 560,
    ppm700Max: 560,
    ph: '5.5 - 6.5',
    volumePerHari: '200-300 ml',
    volumeNumMl: 250,
    frekuensi: '3x',
    fokusKegiatan: 'Air baku murni/nutrisi sangat rendah, adaptasi akar',
    targetKurasKey: 'vegetatif',
    colorBadge: 'bg-blue-600 text-white',
    colorBorder: 'border-blue-500',
  },
  {
    id: 'vegetatif',
    hstMin: 8,
    hstMax: 21,
    fase: 'Vegetatif',
    ecMin: 1.2,
    ecMax: 1.5,
    ppm500Min: 600,
    ppm500Max: 750,
    ppm700Min: 840,
    ppm700Max: 1050,
    ph: '5.8 - 6.2',
    volumePerHari: '500 ml',
    volumeNumMl: 500,
    frekuensi: '4x',
    fokusKegiatan: 'Pupuk daun/N tinggi, pertumbuhan cabang & daun',
    targetKurasKey: 'vegetatif',
    colorBadge: 'bg-emerald-600 text-white',
    colorBorder: 'border-emerald-500',
  },
  {
    id: 'generatif',
    hstMin: 22,
    hstMax: 35,
    fase: 'Generatif Awal / Berbunga',
    ecMin: 1.8,
    ecMax: 2.0,
    ppm500Min: 900,
    ppm500Max: 1000,
    ppm700Min: 1260,
    ppm700Max: 1400,
    ph: '6.0 - 6.5',
    volumePerHari: '800 ml',
    volumeNumMl: 800,
    frekuensi: '5x',
    fokusKegiatan: 'Penyerbukan manual & seleksi buah (pilih buah ruas 9-12)',
    targetKurasKey: 'generatif',
    colorBadge: 'bg-amber-600 text-white',
    colorBorder: 'border-amber-500',
  },
  {
    id: 'pembesaran',
    hstMin: 36,
    hstMax: 55,
    fase: 'Pembesaran Buah',
    ecMin: 2.2,
    ecMax: 2.5,
    ppm500Min: 1100,
    ppm500Max: 1250,
    ppm700Min: 1540,
    ppm700Max: 1750,
    ph: '6.0 - 6.5',
    volumePerHari: '1000-1500 ml',
    volumeNumMl: 1250,
    frekuensi: '6x',
    fokusKegiatan: '+ Kalsium Boron mingguan, cegah buah pecah & kuatkan dinding sel',
    targetKurasKey: 'pembesaran',
    colorBadge: 'bg-purple-600 text-white',
    colorBorder: 'border-purple-500',
  },
  {
    id: 'pematangan',
    hstMin: 56,
    hstMax: 75,
    fase: 'Pematangan / Netting',
    ecMin: 1.8,
    ecMax: 1.8,
    ppm500Min: 900,
    ppm500Max: 900,
    ppm700Min: 1260,
    ppm700Max: 1260,
    ph: '5.8 - 6.2',
    volumePerHari: '500 ml (diturunkan)',
    volumeNumMl: 500,
    frekuensi: '3x',
    fokusKegiatan: 'EC & air diturunkan bertahap untuk menaikkan kadar gula (Brix) & aroma',
    targetKurasKey: 'pematangan',
    colorBadge: 'bg-rose-600 text-white',
    colorBorder: 'border-rose-500',
  },
];

// Tabel Rotasi HPT Mingguan (0 - 75 HST, 11 Minggu)
export const TABEL_ROTASI_HPT: RotasiHptRef[] = [
  {
    minggu: 1,
    hstMin: 0,
    hstMax: 6,
    tipeRotasi: 'Rotasi A',
    insektisida: 'Imidakloprid (Sistemik)',
    fungisida: 'Mankozeb (Kontak)',
    targetOPT: 'Kutu Kebul, Thrips, Rebah Semai (Pythium)',
    dosisAnjuranMin: 1.0,
    dosisAnjuranMax: 2.0,
    dosisAnjuranLabel: '1.0 - 2.0 ml/L',
    isStopPraPanen: false,
    keterangan: 'Pencegahan awal serangga vektor virus gemini & jamur tanah.',
  },
  {
    minggu: 2,
    hstMin: 7,
    hstMax: 13,
    tipeRotasi: 'Rotasi B',
    insektisida: 'Abamektin (Kontak)',
    fungisida: 'Difenokonazol (Sistemik)',
    targetOPT: 'Tungau Merah, Lalat Buah, Powdery Mildew, Busuk Batang',
    dosisAnjuranMin: 1.0,
    dosisAnjuranMax: 2.0,
    dosisAnjuranLabel: '1.0 - 2.0 ml/L',
    isStopPraPanen: false,
    keterangan: 'Pencegahan tungau bawah daun & embun tepung pada daun muda.',
  },
  {
    minggu: 3,
    hstMin: 14,
    hstMax: 20,
    tipeRotasi: 'Rotasi A',
    insektisida: 'Imidakloprid (Sistemik)',
    fungisida: 'Mankozeb (Kontak)',
    targetOPT: 'Kutu Kebul, Thrips, Rebah Semai',
    dosisAnjuranMin: 1.0,
    dosisAnjuranMax: 2.0,
    dosisAnjuranLabel: '1.0 - 2.0 ml/L',
    isStopPraPanen: false,
    keterangan: 'Rotasi kimia golongan neonicotinoid agar hama tidak kebal.',
  },
  {
    minggu: 4,
    hstMin: 21,
    hstMax: 27,
    tipeRotasi: 'Rotasi B',
    insektisida: 'Abamektin (Kontak)',
    fungisida: 'Difenokonazol (Sistemik)',
    targetOPT: 'Tungau, Lalat Penggorok Daun (Liriomyza), Powdery Mildew',
    dosisAnjuranMin: 1.0,
    dosisAnjuranMax: 2.0,
    dosisAnjuranLabel: '1.0 - 2.0 ml/L',
    isStopPraPanen: false,
    keterangan: 'Perlindungan menjelang pembungaan pertama.',
  },
  {
    minggu: 5,
    hstMin: 28,
    hstMax: 34,
    tipeRotasi: 'Rotasi A',
    insektisida: 'Imidakloprid (Sistemik)',
    fungisida: 'Mankozeb (Kontak)',
    targetOPT: 'Thrips pada Bunga, Kutu Daun, Antraknosa',
    dosisAnjuranMin: 1.0,
    dosisAnjuranMax: 2.0,
    dosisAnjuranLabel: '1.0 - 2.0 ml/L',
    isStopPraPanen: false,
    keterangan: 'Semprot sore hari setelah penyerbukan lebah/manual selesai.',
  },
  {
    minggu: 6,
    hstMin: 35,
    hstMax: 41,
    tipeRotasi: 'Rotasi B',
    insektisida: 'Abamektin (Kontak)',
    fungisida: 'Difenokonazol (Sistemik)',
    targetOPT: 'Lalat Buah (Bactrocera), Busuk Batang Berlendir (Gummy Stem Blight)',
    dosisAnjuranMin: 1.0,
    dosisAnjuranMax: 2.0,
    dosisAnjuranLabel: '1.0 - 2.0 ml/L',
    isStopPraPanen: false,
    keterangan: 'Proteksi bakal buah muda pasca seleksi 1 tanaman 1 buah.',
  },
  {
    minggu: 7,
    hstMin: 42,
    hstMax: 48,
    tipeRotasi: 'Rotasi A',
    insektisida: 'Imidakloprid (Sistemik)',
    fungisida: 'Mankozeb (Kontak)',
    targetOPT: 'Kutu Kebul, Thrips, Cacar Daun, Downy Mildew',
    dosisAnjuranMin: 1.0,
    dosisAnjuranMax: 2.0,
    dosisAnjuranLabel: '1.0 - 2.0 ml/L',
    isStopPraPanen: false,
    keterangan: 'Fase pembesaran buah aktif, pastikan daun atas tetap sehat.',
  },
  {
    minggu: 8,
    hstMin: 49,
    hstMax: 55,
    tipeRotasi: 'Rotasi B',
    insektisida: 'Abamektin (Kontak)',
    fungisida: 'Difenokonazol (Sistemik)',
    targetOPT: 'Tungau, Lalat Buah, Powdery Mildew',
    dosisAnjuranMin: 1.0,
    dosisAnjuranMax: 2.0,
    dosisAnjuranLabel: '1.0 - 2.0 ml/L',
    isStopPraPanen: false,
    keterangan: 'Aplikasi terakhir sebelum memasuki batas waktu karantina pra-panen.',
  },
  {
    minggu: 9,
    hstMin: 56,
    hstMax: 60,
    tipeRotasi: 'Rotasi A',
    insektisida: 'Imidakloprid (Dosis Minimal)',
    fungisida: 'Mankozeb (Kontak Dosis Ringan)',
    targetOPT: 'Kutu Kebul / Cek OPT selektif saja',
    dosisAnjuranMin: 1.0,
    dosisAnjuranMax: 1.5,
    dosisAnjuranLabel: '1.0 - 1.5 ml/L (Ringan)',
    isStopPraPanen: false,
    keterangan: 'Waspada HST 60 adalah hari terakhir semprot kimia!',
  },
  {
    minggu: 10,
    hstMin: 61,
    hstMax: 67,
    tipeRotasi: 'Pra-Panen (STOP)',
    insektisida: 'TIDAK DIGUNAKAN (STOP)',
    fungisida: 'TIDAK DIGUNAKAN (STOP)',
    targetOPT: 'Masa Karantina Residu (Pre-Harvest Interval / PHI)',
    dosisAnjuranMin: 0,
    dosisAnjuranMax: 0,
    dosisAnjuranLabel: '0 ml/L (STOP)',
    isStopPraPanen: true,
    keterangan: 'STOP total pestisida! Jaga agar buah bebas dari residu berbahaya.',
  },
  {
    minggu: 11,
    hstMin: 68,
    hstMax: 75,
    tipeRotasi: 'Pra-Panen (STOP)',
    insektisida: 'TIDAK DIGUNAKAN (STOP)',
    fungisida: 'TIDAK DIGUNAKAN (STOP)',
    targetOPT: 'Masa Karantina Residu (Pre-Harvest Interval / PHI)',
    dosisAnjuranMin: 0,
    dosisAnjuranMax: 0,
    dosisAnjuranLabel: '0 ml/L (STOP)',
    isStopPraPanen: true,
    keterangan: 'Panen segera! Pembentukan jaring (netting) sempurna & siap panen.',
  },
];

// Data Default Awal Aplikasi
export const DEFAULT_APP_DATA: MelonAppData = {
  profil: {
    jumlahPolybag: 500,
    varietas: 'Sweet Net (Golden/Alisha type)',
    tanggalTanam: '2026-08-20',
    skalaPPM: 500,
    targetKurasTandonHari: {
      vegetatif: 7,
      generatif: 5,
      pembesaran: 5,
      pematangan: 4,
    },
  },
  logHarian: [
    { hst: 0, tanggal: '2026-08-20', disiram: 'Ya', catatan: 'Pindah tanam bibit 4 daun sejati, cuaca cerah greenhouse 31°C.' },
    { hst: 5, tanggal: '2026-08-25', disiram: 'Ya', catatan: 'Akar mulai keluar polybag, adaptasi baik.' },
    { hst: 12, tanggal: '2026-09-01', disiram: 'Ya', catatan: 'Masuk vegetatif aktif, lilitan ke ajir rajin dilakukan.' },
    { hst: 18, tanggal: '2026-09-07', disiram: 'Ya', catatan: 'Cabang air bawah ruas 8 dipangkas habis.' },
    { hst: 20, tanggal: '2026-09-09', disiram: 'Ya', catatan: 'Kondisi tanaman serempak, vigor daun bagus.' },
  ],
  logTandon: [
    { id: '1', tanggal: '2026-08-20', volumeTandonL: 200, ppmTerukur: 410, aksi: 'Kuras Total', catatan: 'Pengisian nutrisi awal tanam air baku + AB mix EC 0.8' },
    { id: '2', tanggal: '2026-08-27', volumeTandonL: 200, ppmTerukur: 710, aksi: 'Kuras Total', catatan: 'Kuras rutin siklus 7 hari fase vegetatif' },
    { id: '3', tanggal: '2026-09-03', volumeTandonL: 180, ppmTerukur: 680, aksi: 'Kuras Total', catatan: 'Kuras mingguan, larutan stabil pH 6.0' },
    { id: '4', tanggal: '2026-09-08', volumeTandonL: 190, ppmTerukur: 720, aksi: 'Top Up Pekatan', catatan: 'Top up 80ml A dan B menjelang sore' },
  ],
  logHPT: [
    { minggu: 1, dosisDigunakan: 1.5, sudahDisemprot: 'Sudah', catatan: 'Semprot kabut pagi jam 06:30', tanggalSemprot: '2026-08-23' },
    { minggu: 2, dosisDigunakan: 1.5, sudahDisemprot: 'Sudah', catatan: 'Abamektin + Difenokonazol merata bawah daun', tanggalSemprot: '2026-08-30' },
    { minggu: 3, dosisDigunakan: 1.5, sudahDisemprot: 'Sudah', catatan: 'Imidakloprid sistemik, kutu kebul terkendali aman', tanggalSemprot: '2026-09-06' },
    { minggu: 4, dosisDigunakan: 0, sudahDisemprot: 'Belum', catatan: '' },
    { minggu: 5, dosisDigunakan: 0, sudahDisemprot: 'Belum', catatan: '' },
    { minggu: 6, dosisDigunakan: 0, sudahDisemprot: 'Belum', catatan: '' },
    { minggu: 7, dosisDigunakan: 0, sudahDisemprot: 'Belum', catatan: '' },
    { minggu: 8, dosisDigunakan: 0, sudahDisemprot: 'Belum', catatan: '' },
    { minggu: 9, dosisDigunakan: 0, sudahDisemprot: 'Belum', catatan: '' },
    { minggu: 10, dosisDigunakan: 0, sudahDisemprot: 'Belum', catatan: '' },
    { minggu: 11, dosisDigunakan: 0, sudahDisemprot: 'Belum', catatan: '' },
  ],
  stok: {
    sekamL: 2200,
    cocopeatL: 2100,
    koheKg: 1200,
    rasioPekatanA: 5,
    rasioPekatanB: 5,
    kebutuhanSekamPerPolybag: 4,
    kebutuhanCocopeatPerPolybag: 4,
    kebutuhanKohePerPolybag: 2,
    polybagRencanaBatchBerikutnya: 500,
  },
};

export const LOCAL_STORAGE_KEY = 'margamukti_greenhouse_data_v1';
export const LEGACY_STORAGE_KEYS = ['melon_greenhouse_data_v2', 'melon_greenhouse_data'];

/**
 * Buat data awal yang tanggal tanamnya dinamis (-20 hari dari hari ini)
 * agar saat pertama kali dibuka langsung aktif di HST 20 sesuai kalender lokal pengguna
 */
export function getInitialAppData(): MelonAppData {
  const now = new Date();
  // 20 hari sebelum hari ini
  const tanamDate = new Date(now.getFullYear(), now.getMonth(), now.getDate() - 20);
  const pad = (n: number) => String(n).padStart(2, '0');
  const fmt = (d: Date) => `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;
  
  const tanggalTanam = fmt(tanamDate);
  const dHst = (n: number) => {
    const d = new Date(tanamDate);
    d.setDate(d.getDate() + n);
    return fmt(d);
  };

  return {
    profil: {
      jumlahPolybag: 500,
      varietas: 'Sweet Net (Golden/Alisha type)',
      tanggalTanam: tanggalTanam,
      skalaPPM: 500,
      targetKurasTandonHari: {
        vegetatif: 7,
        generatif: 5,
        pembesaran: 5,
        pematangan: 4,
      },
    },
    logHarian: [
      { hst: 0, tanggal: dHst(0), disiram: 'Ya', catatan: 'Pindah tanam bibit 4 daun sejati, cuaca cerah greenhouse 31°C.' },
      { hst: 5, tanggal: dHst(5), disiram: 'Ya', catatan: 'Akar mulai keluar polybag, adaptasi baik.' },
      { hst: 12, tanggal: dHst(12), disiram: 'Ya', catatan: 'Masuk vegetatif aktif, lilitan ke ajir rajin dilakukan.' },
      { hst: 18, tanggal: dHst(18), disiram: 'Ya', catatan: 'Cabang air bawah ruas 8 dipangkas habis.' },
      { hst: 20, tanggal: dHst(20), disiram: 'Ya', catatan: 'Kondisi tanaman serempak, vigor daun bagus.' },
    ],
    logTandon: [
      { id: '1', tanggal: dHst(0), volumeTandonL: 200, ppmTerukur: 410, aksi: 'Kuras Total', catatan: 'Pengisian nutrisi awal tanam air baku + AB mix EC 0.8' },
      { id: '2', tanggal: dHst(7), volumeTandonL: 200, ppmTerukur: 710, aksi: 'Kuras Total', catatan: 'Kuras rutin siklus 7 hari fase vegetatif' },
      { id: '3', tanggal: dHst(14), volumeTandonL: 180, ppmTerukur: 680, aksi: 'Kuras Total', catatan: 'Kuras mingguan, larutan stabil pH 6.0' },
      { id: '4', tanggal: dHst(19), volumeTandonL: 190, ppmTerukur: 720, aksi: 'Top Up Pekatan', catatan: 'Top up 80ml A dan B menjelang sore' },
    ],
    logHPT: [
      { minggu: 1, dosisDigunakan: 1.5, sudahDisemprot: 'Sudah', catatan: 'Semprot kabut pagi jam 06:30', tanggalSemprot: dHst(3) },
      { minggu: 2, dosisDigunakan: 1.5, sudahDisemprot: 'Sudah', catatan: 'Abamektin + Difenokonazol merata bawah daun', tanggalSemprot: dHst(10) },
      { minggu: 3, dosisDigunakan: 1.5, sudahDisemprot: 'Sudah', catatan: 'Imidakloprid sistemik, kutu kebul terkendali aman', tanggalSemprot: dHst(17) },
      { minggu: 4, dosisDigunakan: 0, sudahDisemprot: 'Belum', catatan: '' },
      { minggu: 5, dosisDigunakan: 0, sudahDisemprot: 'Belum', catatan: '' },
      { minggu: 6, dosisDigunakan: 0, sudahDisemprot: 'Belum', catatan: '' },
      { minggu: 7, dosisDigunakan: 0, sudahDisemprot: 'Belum', catatan: '' },
      { minggu: 8, dosisDigunakan: 0, sudahDisemprot: 'Belum', catatan: '' },
      { minggu: 9, dosisDigunakan: 0, sudahDisemprot: 'Belum', catatan: '' },
      { minggu: 10, dosisDigunakan: 0, sudahDisemprot: 'Belum', catatan: '' },
      { minggu: 11, dosisDigunakan: 0, sudahDisemprot: 'Belum', catatan: '' },
    ],
    stok: {
      sekamL: 2200,
      cocopeatL: 2100,
      koheKg: 1200,
      rasioPekatanA: 5,
      rasioPekatanB: 5,
      kebutuhanSekamPerPolybag: 4,
      kebutuhanCocopeatPerPolybag: 4,
      kebutuhanKohePerPolybag: 2,
      polybagRencanaBatchBerikutnya: 500,
    },
  };
}
